# Generated by Django 6.0.4 on 2026-05-26 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_detallepedido_precio_pedido_estado'),
        ('productos', '0007_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.promocion'),
        ),
    ]
